version: '3.7'
services:
  dev:
    build:
      context: ./
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    command: npm run dev
volumes:
  node_modules: